// Generated by modelicac 0.1.0 from model Case21CondExpr.
// 确定性输出：不含时间戳或路径（FR-007）。源模型为唯一事实来源（FR-008）。
#include <cmath>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include "rk4.hpp"
#include "csv_writer.hpp"

struct Vars {
  double y0;  // y0
  double slope;  // slope
  double x;  // state: x
  double y;  // algebraic: y
};

static Vars make_constants() {
  Vars v{};
  v.y0 = 1;
  v.slope = 2;
  return v;
}

static void sync_from_y(const double* y, Vars& v) {
  v.x = y[0];
}

static void sync_to_y(const Vars& v, double* y) {
  y[0] = v.x;
}

static void compute_algebraic(Vars& v) {
  v.y = ((v.x > 1) ? (v.y0 + (v.slope * (v.x - 1))) : (v.y0 + v.x));
}

static void deriv(const Vars& vin, Vars& d) {
  Vars v = vin;
  compute_algebraic(v);
  d.x = 1;
}

int main() {
  const std::string resultPath = "Case21CondExpr_result.csv";

  try {
    Vars v = make_constants();
    v.x = 0;
    const double t0 = 0;
    const double tEnd = 3;
    const long steps = 300L;
    const double h = (tEnd - t0) / static_cast<double>(steps);
    double t = t0;

    mcruntime::CsvWriter csv(resultPath, {"time", "y", "x"});

    std::vector<double> y(1);
    sync_to_y(v, y.data());

    auto rhs = [&](double tt, const double* yy, double* dy) {
      (void)tt;
      Vars s = v;
      sync_from_y(yy, s);
      Vars dd{};
      deriv(s, dd);
      dy[0] = static_cast<double>(dd.x);
    };

    auto writeRow = [&](double rowTime) {
      Vars s = v;
      compute_algebraic(s);
      csv.writeRow(rowTime, {static_cast<double>(s.y), static_cast<double>(s.x)});
    };

    writeRow(t);
    for (long kStep = 0; kStep < steps; ++kStep) {
      mcruntime::rk4_step(h, t, y, rhs);
      sync_from_y(y.data(), v);
      writeRow(t);
    }

    return 0;
  } catch (const std::runtime_error& e) {
    std::fprintf(stderr, "%s\n", e.what());
    std::remove(resultPath.c_str());
    return 3;
  }
}
