// Generated by modelicac 0.1.0 from model Cooling.
// 确定性输出：不含时间戳或路径（FR-007）。源模型为唯一事实来源（FR-008）。
#include <cmath>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include "rk4.hpp"
#include "csv_writer.hpp"
#include "newton.hpp"

struct Vars {
  double k;  // k
  double Tamb;  // Tamb
  double T;  // state: T
};

static Vars make_constants() {
  Vars v{};
  v.k = 0.5;
  v.Tamb = 20;
  return v;
}

static void sync_from_y(const double* y, Vars& v) {
  v.T = y[0];
}

static void sync_to_y(const Vars& v, double* y) {
  y[0] = v.T;
}

static void apply_aliases(Vars& v) {
}

static void compute_algebraic(Vars& v) {
  apply_aliases(v);
}

static void initialize(Vars& v) {
  double der_T = 0.0;
  v.T = 90;
  der_T = 0;
  v.T = 90;
  der_T = ((-v.k) * (v.T - v.Tamb));
  (void)v;
  (void)der_T;
}

static void deriv(const Vars& vin, Vars& d) {
  Vars v = vin;
  compute_algebraic(v);
  d.T = ((-v.k) * (v.T - v.Tamb));
}

int main() {
  const std::string resultPath = "Cooling_result.csv";

  try {
    Vars v = make_constants();
    initialize(v);
    const double t0 = 0;
    const double tEnd = 5;
    const long steps = 500L;
    const double h = (tEnd - t0) / static_cast<double>(steps);
    double t = t0;

    mcruntime::CsvWriter csv(resultPath, {"time", "T"});

    std::vector<double> y(1);
    sync_to_y(v, y.data());

    auto rhs = [&](double tt, const double* yy, double* dy) {
      (void)tt;
      Vars s = v;
      sync_from_y(yy, s);
      Vars dd{};
      deriv(s, dd);
      dy[0] = static_cast<double>(dd.T);
    };

    auto writeRow = [&](double rowTime) {
      Vars s = v;
      compute_algebraic(s);
      csv.writeRow(rowTime, {static_cast<double>(s.T)});
    };

    writeRow(t);
    for (long kStep = 0; kStep < steps; ++kStep) {
      mcruntime::rk4_step(h, t, y, rhs);
      sync_from_y(y.data(), v);
      writeRow(t);
    }

    return 0;
  } catch (const std::runtime_error& e) {
    std::fprintf(stderr, "%s\n", e.what());
    std::remove(resultPath.c_str());
    return 3;
  }
}
