#include "codegen/codegen.h"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <unordered_map>

#ifndef MC_RUNTIME_SRC_DIR
#error "MC_RUNTIME_SRC_DIR 必须由构建系统定义（指向 src/runtime）"
#endif

namespace mcdc {

namespace {

constexpr const char *kGeneratorVersion = "modelicac 0.1.0";
constexpr const char *kRuntimeSrcDir = MC_RUNTIME_SRC_DIR;

// 随生成工程分发的运行时头文件（mcruntime/ 下）。
const std::vector<std::string> kRuntimeFiles = {
    "rk4.hpp",
    "csv_writer.hpp",
};

bool read_whole_file(const std::string &path, std::string *out) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return false;
  std::ostringstream ss;
  ss << in.rdbuf();
  *out = ss.str();
  return true;
}

std::string declTypeName(ast::Component::DeclType type) {
  switch (type) {
  case ast::Component::DeclType::Real:
    return "double";
  case ast::Component::DeclType::Integer:
    return "long long";
  case ast::Component::DeclType::Boolean:
    return "bool";
  }
  return "double";
}

std::string formatReal(double v) {
  char buf[64];
  std::snprintf(buf, sizeof(buf), "%.17g", v);
  return buf;
}

struct EmitCtx {
  const TranslationPlan *plan;
};

std::string emitExpr(const ast::Expr &e, const EmitCtx &ctx) {
  switch (e.kind) {
  case ast::ExprKind::NumLit:
    if (e.token.kind == TokKind::Int)
      return e.token.lexeme;
    return formatReal(e.numValue);
  case ast::ExprKind::BoolLit:
    return e.boolValue ? "true" : "false";
  case ast::ExprKind::Ident: {
    // 查找映射名（状态/代数量/参数常量统一存放于 Vars 成员）。
    for (const auto &var : ctx.plan->states) {
      if (var.sourceName == e.token.lexeme)
        return "v." + var.cppName;
    }
    for (const auto &step : ctx.plan->algebraic) {
      if (step.var.sourceName == e.token.lexeme)
        return "v." + step.var.cppName;
    }
    for (const auto &cp : ctx.plan->constantsParams) {
      if (cp.var.sourceName == e.token.lexeme)
        return "v." + cp.var.cppName;
    }
    throw std::logic_error("未映射的标识符: " + e.token.lexeme);
  }
  case ast::ExprKind::Unary: {
    const std::string operand = emitExpr(*e.lhs, ctx);
    return e.op == "-" ? "(-" + operand + ")" : "(!" + operand + ")";
  }
  case ast::ExprKind::Binary: {
    const std::string l = emitExpr(*e.lhs, ctx);
    const std::string r = emitExpr(*e.rhs, ctx);
    std::string op = e.op;
    if (op == "and")
      op = " && ";
    else if (op == "or")
      op = " || ";
    else if (op == "<>")
      op = " != ";
    else
      op = " " + op + " ";
    return "(" + l + op + r + ")";
  }
  case ast::ExprKind::Call: {
    static const std::unordered_map<std::string, std::string> kFnMap = {
        {"abs", "std::fabs"}, {"sqrt", "std::sqrt"}, {"sin", "std::sin"}, {"cos", "std::cos"},
        {"tan", "std::tan"},  {"exp", "std::exp"},   {"log", "std::log"}, {"log10", "std::log10"},
    };
    std::string fn;
    if (e.op == "min" || e.op == "max") {
      fn = e.op == "min" ? "std::min<double>" : "std::max<double>";
    } else {
      fn = kFnMap.at(e.op);
    }
    std::string out = fn + "(";
    for (size_t i = 0; i < e.args.size(); ++i) {
      if (i > 0)
        out += ", ";
      out += emitExpr(*e.args[i], ctx);
    }
    out += ")";
    return out;
  }
  case ast::ExprKind::Der:
    throw std::logic_error("der(...) 不应残留于表达式树");
  case ast::ExprKind::If:
    // 直线赋值规约（spec 003 D4）：无条件语句级 if/else，仅三元表达式。
    return "(" + emitExpr(*e.cond, ctx) + " ? " + emitExpr(*e.thenExpr, ctx) + " : " +
           emitExpr(*e.elseExpr, ctx) + ")";
  }
  throw std::logic_error("未知表达式类型");
}


} // namespace

GeneratedFiles generateProject(const TranslationPlan &plan, std::string *err) {
  GeneratedFiles files;
  const std::string &m = plan.modelName;
  EmitCtx ctx{&plan};
  std::string body;

  body += "// Generated by " + std::string(kGeneratorVersion) + " from model " + m + ".\n";
  body += "// 确定性输出：不含时间戳或路径（FR-007）。源模型为唯一事实来源（FR-008）。\n";
  body += "#include <cmath>\n#include <cstdio>\n#include <cstring>\n#include <stdexcept>\n#include <string>\n";
  body += "#include <vector>\n\n#include \"rk4.hpp\"\n#include \"csv_writer.hpp\"\n\n";

  // ---- Vars 结构 ----
  body += "struct Vars {\n";
  for (const auto &cp : plan.constantsParams) {
    body += "  " + declTypeName(cp.var.type) + " " + cp.var.cppName + ";  // " + cp.var.sourceName +
            "\n";
  }
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "  " + declTypeName(plan.states[i].type) + " " + plan.states[i].cppName +
            ";  // state: " + plan.states[i].sourceName + "\n";
  }
  for (const auto &step : plan.algebraic) {
    body += "  " + declTypeName(step.var.type) + " " + step.var.cppName +
            ";  // algebraic: " + step.var.sourceName + "\n";
  }
  body += "};\n\n";

  // ---- 常量/参数 ----
  body += "static Vars make_constants() {\n  Vars v{};\n";
  for (const auto &cp : plan.constantsParams) {
    body += "  v." + cp.var.cppName + " = " + cp.initLiteral + ";\n";
  }
  body += "  return v;\n}\n\n";

  // ---- 状态同步 ----
  body += "static void sync_from_y(const double* y, Vars& v) {\n";
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "  v." + plan.states[i].cppName + " = y[" + std::to_string(i) + "];\n";
  }
  body += "}\n\nstatic void sync_to_y(const Vars& v, double* y) {\n";
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "  y[" + std::to_string(i) + "] = v." + plan.states[i].cppName + ";\n";
  }
  body += "}\n\n";

  // ---- 代数量（拓扑序）----
  body += "static void compute_algebraic(Vars& v) {\n";
  for (const auto &step : plan.algebraic) {
    body += "  v." + step.var.cppName + " = " + emitExpr(*step.rhs, ctx) + ";\n";
  }
  body += "}\n\n";

  // ---- 导数 ----
  body += "static void deriv(const Vars& vin, Vars& d) {\n  Vars v = vin;\n"
          "  compute_algebraic(v);\n";
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "  d." + plan.states[i].cppName + " = " + emitExpr(*plan.stateRhs[i], ctx) + ";\n";
  }
  body += "}\n\n";

  // ---- main ----
  body += "int main() {\n";
  body += "  const std::string resultPath = \"" + m + "_result.csv\";\n\n";
  body += "  try {\n    Vars v = make_constants();\n";
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "    v." + plan.states[i].cppName + " = " + plan.stateInitLiterals[i] + ";\n";
  }
  body += "    const double t0 = " + formatReal(plan.startTime) + ";\n";
  body += "    const double tEnd = " + formatReal(plan.stopTime) + ";\n";
  body += "    const long steps = " + std::to_string(plan.steps) + "L;\n";
  body += "    const double h = (tEnd - t0) / static_cast<double>(steps);\n";
  body += "    double t = t0;\n\n";

  body += "    mcruntime::CsvWriter csv(resultPath, {\"time\"";
  for (const auto &var : plan.outputOrder) {
    body += ", \"" + var.sourceName + "\"";
  }
  body += "});\n\n";

  body += "    std::vector<double> y(" + std::to_string(plan.states.size()) + ");\n";
  body += "    sync_to_y(v, y.data());\n\n";

  body += "    auto rhs = [&](double tt, const double* yy, double* dy) {\n";
  body += "      (void)tt;\n      Vars s = v;\n      sync_from_y(yy, s);\n      Vars dd{};\n";
  body += "      deriv(s, dd);\n";
  for (size_t i = 0; i < plan.states.size(); ++i) {
    body += "      dy[" + std::to_string(i) + "] = static_cast<double>(dd." +
            plan.states[i].cppName + ");\n";
  }
  body += "    };\n\n";

  body += "    auto writeRow = [&](double rowTime) {\n      Vars s = v;\n";
  body += "      compute_algebraic(s);\n      csv.writeRow(rowTime, {";
  for (size_t i = 0; i < plan.outputOrder.size(); ++i) {
    if (i > 0)
      body += ", ";
    body += "static_cast<double>(s." + plan.outputOrder[i].cppName + ")";
  }
  body += "});\n";
  body += "    };\n\n";

  body += "    writeRow(t);\n";
  body += "    for (long kStep = 0; kStep < steps; ++kStep) {\n";
  body += "      mcruntime::rk4_step(h, t, y, rhs);\n";
  body += "      sync_from_y(y.data(), v);\n      writeRow(t);\n    }\n\n";

  body += "    return 0;\n";
  body += "  } catch (const std::runtime_error& e) {\n";
  body += "    std::fprintf(stderr, \"%s\\n\", e.what());\n";
  body += "    std::remove(resultPath.c_str());\n    return 3;\n  }\n}\n";

  files.emplace("model_" + m + ".cpp", std::move(body));

  // ---- CMakeLists.txt ----
  std::string cmake;
  cmake += "cmake_minimum_required(VERSION 3.24)\n";
  cmake += "# 由 " + std::string(kGeneratorVersion) + " 生成。第三方依赖：无（仅标准库）。\n";
  cmake += "# FR-002 政策：如需引入开源数学库，必须在此显式固定版本并声明来源。\n";
  cmake += "project(" + m + " LANGUAGES CXX)\n";
  cmake += "set(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
  cmake += "if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)\n";
  cmake += "  set(CMAKE_BUILD_TYPE Release CACHE STRING \"\" FORCE)\nendif()\n";
  cmake += "add_executable(" + m + " model_" + m + ".cpp)\n";
  cmake += "target_include_directories(" + m + " PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/mcruntime)\n";
  files.emplace("CMakeLists.txt", std::move(cmake));

  // ---- 运行时头文件（从 MC_RUNTIME_SRC_DIR 读入，单一事实来源）----
  for (const auto &name : kRuntimeFiles) {
    std::string content;
    if (!read_whole_file(std::string(kRuntimeSrcDir) + "/" + name, &content)) {
      if (err)
        *err = std::string("无法读取运行时源文件: ") + kRuntimeSrcDir + "/" + name;
      return {};
    }
    files.emplace("mcruntime/" + name, std::move(content));
  }
  return files;
}

bool writeProject(const GeneratedFiles &files, const std::string &outDir, std::string *err) {
  namespace fs = std::filesystem;
  try {
    fs::create_directories(outDir + "/mcruntime");
    for (const auto &[name, content] : files) {
      const std::string path = outDir + "/" + name;
      fs::create_directories(fs::path(path).parent_path());
      std::ofstream out(path, std::ios::binary);
      if (!out) {
        if (err)
          *err = "无法写入文件: " + path;
        return false;
      }
      out.write(content.data(), static_cast<std::streamsize>(content.size()));
      if (!out) {
        if (err)
          *err = "写入失败: " + path;
        return false;
      }
    }
    return true;
  } catch (const std::exception &e) {
    if (err)
      *err = e.what();
    return false;
  }
}

} // namespace mcdc
