# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++17
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Hello -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lryu -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/wsl-ubuntu-1/projects/pocmodelica/example/hello_omc"
MAINFILE=Hello.c
MAINOBJ=Hello.o
CFILES=Hello_functions.c Hello_records.c \
Hello_01exo.c Hello_02nls.c Hello_03lsy.c Hello_04set.c Hello_05evt.c Hello_06inz.c Hello_07dly.c \
Hello_08bnd.c Hello_09alg.c Hello_10asr.c Hello_11mix.c Hello_12jac.c Hello_13opt.c Hello_14lnz.c \
Hello_15syn.c Hello_16dae.c Hello_17inl.c Hello_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Hello.makefile Hello_literals.h Hello_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Hello_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Hello_functions.h Hello_literals.h $(OFILES)
	$(CC) -I. -o Hello$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) Hello_functions.h Hello_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o Hello$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f Hello_records.o $(MAINOBJ)

bundle:
	@tar -cvf Hello_Files.tar $(GENERATEDFILES)