/* Additional record code for Hello generated by the OpenModelica Compiler OpenModelica 1.27.0~5-ga0783c0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Hello_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

